name: bmi
description: bmi calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
